services:
  db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=taxi-trip-service-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: