spring:
  datasource:
    url: jdbc:postgresql://db:5432/taxi-trip-service-db
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

async-timeout-millis: 600000
rebalance-threshold: 0.80

excel:
  export:
    sheet:
      prefix: "trips_"
      max-rows: 1000000
    performance:
      batch-size: 100000