spring:
  datasource:
    url: jdbc:postgresql://db:5432/taxi-trip-service-db
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

async-timeout-millis: 600000
excel:
  export:
    sheet:
      prefix: "trips_"
      max-rows: 1048576
    performance:
      batch-size: 100000

favorite-trip-list:
  position-gap: 10000000
  initial-position: 10000000
  min-gap: 100
  rebalance-threshold: 0.8