spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi-trip-service-db
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration