-- V1__Create_weather_observations.sql

CREATE TABLE IF NOT EXISTS public.weather_observations
(
    weather_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    station_id character varying(255),
    station_name character varying(255),
    date date,
    average_wind_speed double precision,
    precipitation double precision,
    snow_depth double precision,
    snowfall double precision,
    max_temperature bigint,
    min_temperature bigint,
    CONSTRAINT weather_observations_pkey PRIMARY KEY (weather_id),
    CONSTRAINT weather_observations_date_unique UNIQUE (date)
);

ALTER TABLE public.weather_observations
ADD CONSTRAINT unique_weather_date UNIQUE (date);

CREATE INDEX IF NOT EXISTS idx_weather_wind_speed
    ON public.weather_observations (average_wind_speed);

CREATE INDEX IF NOT EXISTS idx_weather_date_wind_speed
    ON public.weather_observations (date, average_wind_speed);

CREATE INDEX IF NOT EXISTS idx_weather_observations_date
    ON public.weather_observations (date ASC NULLS LAST);

INSERT INTO public.weather_observations
(station_id, station_name, date, average_wind_speed, precipitation, snow_depth, snowfall, max_temperature, min_temperature, weather_id)
VALUES
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-01', 7.61, 0, 0, 0, 42, 34, 2557),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-02', 6.71, 0, 0, 0, 40, 32, 2558),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-03', 7.83, 0, 0, 0, 45, 35, 2559),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-04', 8.5, 0, 0, 0, 36, 14, 2560),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-05', 5.14, 0, 0, 0, 29, 11, 2561),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-06', 3.58, 0, 0, 0, 41, 25, 2562),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-07', 2.46, 0, 0, 0, 46, 31, 2563),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-08', 4.25, 0, 0, 0, 46, 31, 2564),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-09', 8.05, 0, 0, 0, 47, 40, 2565),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-10', 9.84, 1.8, 0, 0, 59, 40, 2566),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-11', 10.51, 0, 0, 0, 40, 26, 2567),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-12', 6.04, 0, 0, 0, 44, 25, 2568),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-13', 9.84, 0, 0, 0, 30, 22, 2569),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-14', 4.92, 0, 0, 0, 38, 22, 2570),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-15', 5.14, 0, 0, 0, 51, 34, 2571),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-16', 6.71, 0.24, 0, 0, 52, 42, 2572),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-17', 5.59, 0.05, 0.4, 0, 42, 30, 2573),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-18', 11.86, 0, 0, 0, 31, 18, 2574),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-19', 10.96, 0, 0, 0, 28, 16, 2575),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-20', 5.59, 0, 0, 0, 37, 27, 2576),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-21', 6.04, 0, 0, 0, 36, 26, 2577),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-22', 6.49, 0.01, 0.2, 0, 30, 21, 2578),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-23', 15.66, 2.31, 27.3, 5.9, 27, 24, 2579),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-24', 5.82, 0, 0, 22, 35, 20, 2580),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-25', 3.36, 0, 0, 18.9, 39, 28, 2581),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-26', 6.49, 0, 0, 16.9, 48, 38, 2582),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-27', 6.71, 0, 0, 9.1, 47, 34, 2583),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-28', 4.47, 0, 0, 5.9, 42, 32, 2584),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-29', 7.83, 0, 0, 5.9, 41, 30, 2585),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-30', 6.93, 0, 0, 5.9, 39, 28, 2586),
('USW00094728', 'NY CITY CENTRAL PARK, NY US', '2016-01-31', 5.14, 0, 0, 3.9, 56, 36, 2587);