-- V2__Create_trips.sql

CREATE TABLE IF NOT EXISTS public.trips
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    vendor_id integer,
    pickup_datetime timestamp without time zone,
    dropoff_datetime timestamp without time zone,
    passenger_count integer,
    trip_distance double precision,
    rate_code_id integer,
    store_and_fwd_flag character varying(255),
    pickup_location_id integer,
    dropoff_location_id integer,
    payment_type integer,
    fare_amount double precision,
    extra double precision,
    mta_tax double precision,
    tip_amount double precision,
    tolls_amount double precision,
    improvement_surcharge double precision,
    total_amount double precision,
    congestion_surcharge double precision,
    airport_fee double precision,
    pickup_date DATE GENERATED ALWAYS AS (date(pickup_datetime)) STORED,
    CONSTRAINT trips_pkey PRIMARY KEY (id),
    CONSTRAINT fk_weather_observations FOREIGN KEY (pickup_date)
        REFERENCES public.weather_observations (date)
);

CREATE INDEX IF NOT EXISTS idx_trips_pickup_datetime
    ON public.trips (pickup_datetime);

CREATE INDEX IF NOT EXISTS idx_trips_pickup_date_weather_id
    ON public.trips (pickup_date, id);

CREATE INDEX IF NOT EXISTS idx_trips_pickup_date
    ON public.trips (pickup_date);

INSERT INTO public.trips
(id, vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, rate_code_id, store_and_fwd_flag, pickup_location_id, dropoff_location_id, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, airport_fee)
VALUES
(1, 1, '2016-01-29 23:57:48', '2016-01-30 00:04:42', 1, 1.1, 1, 'N', 143, 238, 1, 7, 0.5, 0.5, 0.5, 0, 0.3, 8.8, NULL, NULL),
(2, 1, '2016-01-29 23:12:38', '2016-01-29 23:34:26', 1, 1.9, 1, 'N', 107, 148, 1, 14.5, 0.5, 0.5, 3.16, 0, 0.3, 18.96, NULL, NULL),
(3, 1, '2016-01-29 23:36:29', '2016-01-29 23:56:04', 1, 2.8, 1, 'N', 148, 90, 1, 14, 0.5, 0.5, 1, 0, 0.3, 16.3, NULL, NULL);