-- V3__Create_favorite_trips.sql

CREATE TABLE IF NOT EXISTS public.favorite_trips
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    trip_id bigint,
    position bigint,
    version bigint,
    CONSTRAINT favorite_trips_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_favorite_trips_trip_id
    ON public.favorite_trips USING btree
    (trip_id ASC NULLS LAST);

INSERT INTO public.favorite_trips (trip_id, position, version) VALUES
(1, 1, 0),
(2, 2, 0),
(3, 3, 0);